# This is free software,  Licensed to the public under the GPL V3 License.

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for strongswan
LUCI_DEPENDS:=+strongswan

PKG_LICENSE:=GPL-3.0-or-later
PKG_MAINTAINER:=Dengfeng Liu <liudf0716@gmail.com>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
