# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=Dengfeng Liu <liudf0716@gmail.com>

LUCI_TITLE:=LuCI support for alist
LUCI_DEPENDS:=+alist


include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
