# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_LICENSE=Apache-2.0

LUCI_TITLE:=A Declarative Framework for Rapid Construction of Web-based Visualization 

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
